# Generated by Django 3.0.7 on 2020-06-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='None', max_length=100)),
                ('last_name', models.CharField(default='None', max_length=100)),
                ('middle_name', models.CharField(default='None', max_length=100)),
                ('preffered_name', models.CharField(default='None', max_length=100)),
                ('mobile_no', models.IntegerField(default=0)),
                ('email', models.CharField(default='None', max_length=1000)),
                ('organization', models.CharField(default='None', max_length=100)),
                ('gender', models.CharField(default='None', max_length=1000)),
                ('street', models.CharField(default='None', max_length=1000)),
                ('state', models.CharField(default='None', max_length=1000)),
                ('city', models.CharField(default='None', max_length=1000)),
                ('country', models.CharField(default='None', max_length=1000)),
                ('zipcode', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(default='9999-12-31 23:59:59')),
                ('updated_on', models.DateTimeField(default='9999-12-31 23:59:59')),
            ],
        ),
    ]
