# Generated by Django 3.0.7 on 2020-06-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eSignApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='None', max_length=1000),
        ),
    ]
