# Generated by Django 3.0.7 on 2020-06-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eSignApp', '0002_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=0)),
                ('image', models.CharField(default='None', max_length=10000000000)),
                ('created_on', models.DateTimeField(default='9999-12-31 23:59:59')),
                ('updated_on', models.DateTimeField(default='9999-12-31 23:59:59')),
            ],
        ),
    ]
