# Generated by Django 3.0.7 on 2020-06-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eSignApp', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='preffered_name',
            field=models.CharField(default='None', max_length=10000),
        ),
    ]
