# Generated by Django 3.0.7 on 2020-06-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eSignApp', '0004_image_preffered_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preffered_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default='None', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(default='None', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(default='None', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='street',
            field=models.CharField(default='None', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='zipcode',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
