# Generated by Django 3.0.7 on 2020-07-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eSignApp', '0005_auto_20200629_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_image',
            field=models.IntegerField(default=0),
        ),
    ]
