# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnh_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='email',
            field=models.CharField(default='None', max_length=1000),
        ),
    ]
