# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnh_app', '0002_subscription_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='source_of_knowledge',
            new_name='source_of_information',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='subscription',
            new_name='subscriptionDuration',
        ),
        migrations.AddField(
            model_name='subscription',
            name='juices',
            field=models.CharField(default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_method',
            field=models.CharField(default='None', max_length=1000),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='medical_condition',
            field=models.CharField(default='None', max_length=1000, null=True),
        ),
    ]
