# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnh_app', '0003_auto_20180725_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
