# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-03 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnh_app', '0004_auto_20180725_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.CharField(default='None', max_length=1000, null=True),
        ),
    ]
