# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-03 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnh_app', '0005_auto_20180803_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
